version: '3'
services:
  ansible:
    image: ansible
    volume:
      - /home/tnguye20/docker/volume/ansible/:/ansible
      - /home/tnguye20/docker/volume/scripts/:/scripts
    entrypoint: /home/tnguye20/docker/entry/ansible-entrypoint.sh
    extra-hosts:
      - self:127.0.0.1
    tty: true
    restart: "no"
