version: '3'
services:
  ansible:
    image: node:latest
     volume:
       - /home/tnguye20/docker/volume/node/:/ansible
       - /home/tnguye20/docker/volume/scripts/:/scripts
    entrypoint: /home/tnguye20/docker/entry/ansible-entrypoint.sh
    ports:
      - "8080:8080"
      - "80:80"
      - "22:22"
      - "443:443"
      - "8026:8026"
    extra_hosts:
      - self:127.0.0.1
    tty: true
    restart: "no"
